image: ruby:2.4.2

stages:
  - stage
  - theend

variables:
 DATABASE_URL: 'mongodb://mongo/user_posts'
 DOCKER_HOST: tcp://docker:2375/
 DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
 - cd reddit
 - bundle install

.install_docker: &install_docker |
 export DOCKER_REPO="jessie"
 apt-get update
 apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
 curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
 add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $DOCKER_REPO stable"
 apt-get update && apt-get -y install docker-ce

.create_container_dh: &create_container_dh |
 docker login -u "$DH_REGISTRY_USER" -p "$DH_REGISTRY_PASSWORD"
 cd .. 
 docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
 docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

.deploy_container_gce: &deploy_container_gce |
 gcloud compute ssh gitlab-gcp-vm-$CI_COMMIT_REF_SLUG --force-key-file-overwrite --zone europe-west1-b --command "docker login -u $DH_REGISTRY_USER -p $DH_REGISTRY_PASSWORD && sudo docker run -i$DH_REGISTRY_USER/otus-gitlab-ci:$CI_COMMIT_REF_SLUG"

.install_gcloud: &install_gcloud |
 export CLOUD_SDK_REPO="cloud-sdk-jessie"
 echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
 curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
 apt-get update && apt-get -y install google-cloud-sdk
 echo $DEPLOY_KEY_FILE > /tmp/$CI_COMMIT_REF_SLUG.json
 gcloud auth activate-service-account --key-file /tmp/$CI_COMMIT_REF_SLUG.json
 echo "Gcloud installed"

.create_gcp_vm: &create_gcp_vm |
 gcloud compute instances create gitlab-gcp-vm-$CI_COMMIT_REF_SLUG --project $PROJECT_ID --tags=gitlab-deploy-server,http-server,https-server  --image-family docker-host --preemptible --zone europe-west1-b
 echo "New VM - gitlab-gcp-vm-$CI_COMMIT_REF_SLUG created"

.delete_gcp_vm: &delete_gcp_vm |
 gcloud compute instances delete gitlab-gcp-vm-$CI_COMMIT_REF_SLUG --project $PROJECT_ID --zone=europe-west1-b  --quiet
 echo "Delete VM - gitlab-gcp-vm-$CI_COMMIT_REF_SLUG"

staging:
  stage: stage
  when: manual
  script:
    - *install_gcloud
    - *create_gcp_vm
    - *deploy_container_gce
    - echo 'Deploy'
  environment:
    name: stage
    url: http://beta.example.com

delete vm:
 stage: theend
 when: manual
 script:
   - *install_gcloud
   - *delete_gcp_vm


