image: ruby:2.4.2

stages:
  - build
  - test
  - deploy
variables:
 DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
 - cd reddit 
 - bundle install

build_job:
  stage: build
  tags:
    - linux
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  tags:
    - linux
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb 

test_integration_job:
  stage: test
  tags:
    - linux
  script:
    - echo 'Testing 2'

deploy_job:
  stage: deploy
  tags:
    - linux
  script:
    - echo 'Deploy'
