image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
 DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
 - export CLOUD_SDK_REPO="cloud-sdk-$jessie"
 - echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
 - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
 - apt-get update && sudo apt-get install google-cloud-sdk
 - cd reddit
 - bundle install

.bundle_gcp_vm: &bundle_gcp_vm |
 echo $DEPLOY_KEY_FILE > /tmp/$CI_PIPELINE_ID.json
 gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
 gcloud compute instances create gitlab-gcp-vm-$CI_PIPELINE_ID --project $PROJECT_ID --tags=gitlab-env-server  --image-family docker-host --preemptible --zone europe-west1-b
 echo "New VM - gitlab-gcp-vm-$CI_PIPELINE_ID created"

build_job:
  stage: build
  tags:
    - linux
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  tags:
    - linux
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  tags:
    - linux
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  tags:
    - linux
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
 stage: review
 script:
   - echo "Deploy to $CI_ENVIRONMENT_SLUG"
   - *bundle_gcp_vm
 environment:
   name: branch/$CI_COMMIT_REF_NAME
   url: http://$CI_ENVIRONMENT_SLUG.example.com
 only:
   - branches
 except:
   - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com

