dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: Lc9pGiZGNgi6yZXatWYIlxpaHPsflnoQpnIKyaTmqg5k0mIWEOy13tVDqaA93RtHfNPEf4o6vkfNeT1B8qQsLss4HamoUbBfr0NbdjwcrNrFH5Rhdbc9vQahxw7VcQDJIqPrr/SX+RActWqahe1fLn5bW4l5ghYokbqAamwfO2TA1Iq38dWjA/qcsxvVnjxeTtLoB9Jc81y+tMMBr7xhqjE7au6/18iiP0KrKtdnT045q2TcMiHhIr55PcRLNi2HI96X8/1sM7bTkq4MZciEqV55Pu8bK/JPX5E6z7RKlgkoLLeNrIVWsPz6uzf/TiRwrjvgw9gEOQX25JpFzgF7mtcDeIMREreaG1DH8JgpfvkggODSXHk3PBOdoIMKI+4MzAd3WMKdejBD97J/SQhdPQHBKEO2GrZcgOhpK2vnzBAJTHGpIBzWcx2KjMqIu4WZXsla9fIMTnYSkTYSLNmx4gyyzu7RqZdb8lC62epxBQvmTtlAFka/ZmVppLnjpmGg19dfgi4/PB1CPwPjCehwY4U+0wzPDnL0coDXuXizV8zmX1UTMrU2jWEuoK2pZVV4OL7PLoIrpe34KhiCQE21eXkHp+XdZBaVxqQ+SPmfgimeJfndVvoGK+duIfvpjxL7PTpcgA6eOVxVY3St8x69qSx5Wsni89Nu+qICLFWiWkU=
