global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#taras_zaviryukha'

  - name: 'email'
  email_configs:
    - to: username@gmail.com
      from: username@gmail.com
      smarthost: smtp.gmail.com:587
      auth_username: "username@gmail.com"
      auth_identity: "username@gmail.com"
      auth_password: "secret"
