---
- name: Run container 
  hosts: tag_docker-host
  become: yes
  become_method: sudo

  vars_files:
    - ../secrets.yml
    - ../vars.yml

  tasks:
  - name: login to docker registry
    docker_login:
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      email: "{{ docker_hub_email }}"
    tags: deploy-tag
  
  - name: Container present
    docker_container:
      name: "{{ container_name }}"
      state: present
      image: "{{ image_name }}"
      command: sleep infinit
    tags: deploy-tag  

  - name: Started container
    docker_container:
      name: "{{ container_name }}"
      image: "{{ image_name }}" 
      state: started
      exposed_ports:
        - 9292
      ports:
        - "9292:9292"
    tags: start-tag

