---
- name: Run docker-compose for gitlab
  hosts: gitlab-ci
  become: true
 
  tasks:
    - name: Creates directory
      file: path=/srv/gitlab/config state=directory
    - name: Creates directory
      file: path=/srv/gitlab/data state=directory
    - name: Creates directory
      file: path=/srv/gitlab/logs state=directory

    - name: Change gitlab config file
      template:
        src: ../templates/docker-compose.yml
        dest: /srv/gitlab/docker-compose.yml
        mode: 0644

    - name: run the service defined in my_project's docker-compose.yml
      docker_service:
        project_src: /srv/gitlab
