version: '3.3'
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
         - comment_db

  ui:
    image: ${USER_NAME}/ui:latest
    ports:
      - ${PORT_HOST}:${PORT_CONTAINER}/tcp
    networks:
      - front_net

  post:
    image: ${USER_NAME}/post:latest
    networks:
      - back_net
      - front_net

  comment:
    image: ${USER_NAME}/comment:latest
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 10.0.2.0/24
  metrics_net:
